[package]
authors = ["Eric Kidd <git@randomhacks.net>"]
description = "Fetch secrets from either environment variables or Hashicorp's Vault"
documentation = "http://docs.rs/credentials/"
license = "CC0-1.0"
name = "credentials"
readme = "README.md"
repository = "https://github.com/emk/credentials"
version = "0.7.0"

[dependencies]
error-chain = "0.10"
hyper = { version = "0.11", default-features = false }
lazy_static = "0.2"
log = "0.3.5"
regex = "0.2"
reqwest = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
env_logger = "0.4"
