[package]
authors = ["Eric Kidd <git@randomhacks.net>"]
description = "Fetch secrets from either environment variables or Hashicorp's Vault"
documentation = "http://docs.randomhacks.net/credentials/"
license = "CC0-1.0"
name = "credentials"
readme = "README.md"
repository = "https://github.com/emk/credentials"
version = "0.4.1"

[dependencies]
error-chain = "0.5.0"
hyper = { version = "0.9", default-features = false }
lazy_static = "0.2.2"
log = "0.3.5"
regex = "0.1.58"
reqwest = "0.1.0"
rustc-serialize = "0.3.18"

[dev-dependencies]
env_logger = "0.3.2"

[features]
# Required by `travis-cargo`.
unstable = []
