[package]
authors = ["Eric Kidd <git@randomhacks.net>"]
description = "Fetch secrets from either environment variables or Hashicorp's Vault"
documentation = "http://docs.randomhacks.net/credentials/"
license = "CC0-1.0"
name = "credentials"
readme = "README.md"
repository = "https://github.com/emk/credentials"
version = "0.1.1"

[dependencies]
hyper = "0.8.0"
lazy_static = "0.1.15"
log = "0.3.5"
regex = "0.1.58"
rustc-serialize = "0.3.18"

[dev-dependencies]
env_logger = "0.3.2"
yup-hyper-mock = "1.3.2"

[features]
unstable = []
