[package]
name = "credentials"
version = "0.0.1"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Access secure credentials at runtime from multiple backends (work in progress)"
license = "Apache-2.0/MIT"
readme = "README.md"

repository = "https://github.com/emk/credentials"

[dependencies]
